### ISSUE TITLE
SwapRoutes tests fail on macOS

### ISSUE THREAD

**Issue by leonlan** [PyVRP/PyVRP#371]
When running the tests of swap routes, I get an error:
```
pyvrp/search/tests/test_SwapRoutes.py ..Fatal Python error: Aborted

Current thread 0x0000000202b42080 (most recent call first):
  File "/Users/leonlan/Dropbox/PyVRP/pyvrp/search/tests/test_SwapRoutes.py", line 36 in test_apply
	...
Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, numpy.linalg.lapack_lite, matplotlib._c_internal_utils, PIL._imaging, matplotlib._path, kiwisolver._cext, matplotlib._image, matplotlib.backends._macosx (total: 20)
[1]    84851 abort      poetry run pytest
```

Specifically, these tests fail:
https://github.com/PyVRP/PyVRP/blob/f246c30322ae4f059aca191eeffa0c225592faae/pyvrp/search/tests/test_SwapRoutes.py#L17-L20

**Comment by leonlan** [comment]
I have a hard time getting the debugger to work. (Specifically, I can attach to Python process with lldb and step into the C++ calls, but I can't get source code to appear in lldb only machine instructions.)

Anyway, isolating the test and running it in this `script.py`:

<details>
<summary>script.py</summary>

```python
from typing import List

import pytest
from numpy.testing import assert_, assert_allclose, assert_equal

from pyvrp import CostEvaluator, VehicleType
from pyvrp.search import SwapRoutes
from pyvrp.search._search import Node, Route
from pyvrp.tests.helpers import make_heterogeneous, read

L = [
    ([], [1]),  # first empty, second non-empty
    ([1], [2, 3]),  # both non-empty but unequal length
    ([2, 3], [1]),  # both non-empty but unequal length (flipped)
    ([2, 3], [1, 4]),  # both non-empty equal length
]


def test_apply(visits1: List[int], visits2: List[int]):
    """
    Tests that applying SwapRoutes to two different routes indeed exchanges
    the visits.
    """
    data = read("data/OkSmall.txt")

    route1 = Route(data, idx=0, vehicle_type=0)
    for loc in visits1:
        route1.append(Node(loc=loc))

    route2 = Route(data, idx=1, vehicle_type=0)
    for loc in visits2:
        route2.append(Node(loc=loc))

    route1.update()
    route2.update()

    # Before calling apply, route1 visits the clients in visits1, and route2
    # visits the clients in visits2.
    assert_equal(visits1, [node.client for node in route1])
    assert_equal(visits2, [node.client for node in route2])

    op = SwapRoutes(data)
    op.apply(route1, route2)

    # But after apply, the visits are now swapped.
    assert_equal(visits2, [node.client for node in route1])
    assert_equal(visits1, [node.client for node in route2])


for v1, v2 in L:
    test_apply(v1, v2)
```

</details>

results in the following error:
```
Python(95471,0x202b42080) malloc: Heap corruption detected, free list is damaged at 0x600002da3fe0
*** Incorrect guard value: 0
Python(95471,0x202b42080) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    95471 abort      poetry run python pyvrp/script.py
```

However, the failure sometimes doesn't occur (like one out of 10 times).

**Comment by N-Wouda** [comment]
Perhaps superfluous: I ran the above script ten times through the debugger (gdb) on my platform (Ubuntu). No issues. I don't know if I can be of much help debugging this issue.

**Comment by leonlan** [comment]
I'm going to pause working on this because I just can't figure it out. I'll just continue working while commenting this test out.

Some things I have tried:
- Benchmarking all GH and X instances for 1 second with only SwapRoutes does not lead to any problems.
- I have added print statements in many places of the source code. But it is impossible to find the exact place where the fault occurs. From running the script above, it seems that the error mostly happens when doing something with route 2. Sometimes it's when constructing the route, sometimes it's when inserting the node, ...


<details>
<summary>Updated script.py with print statements</summary>
from typing import List

import pytest
from numpy.testing import assert_, assert_allclose, assert_equal

from pyvrp import CostEvaluator, VehicleType
from pyvrp.search._search import Node, Route
from pyvrp.tests.helpers import make_heterogeneous, read


def test_apply(visits1: List[int], visits2: List[int]):
    """
    Tests that applying SwapRoutes to two different routes indeed exchanges
    the visits.
    """
    print("Py: New test.")
    data = read("data/OkSmall.txt")

    print("Py: Create route 1.")
    route1 = Route(data, idx=0, vehicle_type=0)
    for idx, loc in enumerate(visits1):
        print(f"Py: Start insert node: {idx}/{len(visits1)-1}")
        route1.append(Node(loc=loc))
        print(f"Py: End insert node: {idx}/{len(visits1)-1}")

    print("Py: Create route 2.")
    route2 = Route(data, idx=1, vehicle_type=0)
    for idx, loc in enumerate(visits2):
        print(f"Py: Start insert node: {idx}/{len(visits2)-1}")
        route2.append(Node(loc=loc))
        print(f"Py: End insert node: {idx}/{len(visits2)-1}")

    print("Py: Update route 1.")
    route1.update()

    print("Py: Update route 2.")
    route2.update()

    # Before calling apply, route1 visits the clients in visits1, and route2
    # visits the clients in visits2.
    assert_equal(visits1, [node.client for node in route1])
    assert_equal(visits2, [node.client for node in route2])

    from pyvrp.search import SwapRoutes

    op = SwapRoutes(data)
    op.apply(route1, route2)

    print("Py: after apply.")

    # But after apply, the visits are now swapped.
    assert_equal(visits2, [node.client for node in route1])
    assert_equal(visits1, [node.client for node in route2])


L = [
    ([], [1]),  # first empty, second non-empty
    ([1], [2, 3]),  # both non-empty but unequal length
    ([2, 3], [1]),  # both non-empty but unequal length (flipped)
    ([2, 3], [1, 4]),  # both non-empty equal length
]


for v1, v2 in L:
    test_apply(v1, v2)



</details>

**Comment by leonlan** [comment]
That's interesting, because the MacBook Pro 2017 is Intel-based. So this issue may be specific to macOS.

**Comment by leonlan** [comment]
Hmm it's getting interesting. While working on #369 I uncommented the SwapRoutes tests, but now the`test_wrong_load_calculation_bug()` in SwapStar now also fails.

**Comment by leonlan** [comment]
After realizing that SwapStar also fails, I figured that it must have been some way earlier commit that caused this issue.

I've managed to isolate the specific commit that introduced the failing bug (see detail below), which is a12c4fb.

<details>
<summary>Finding the commit</summary>
Ticked boxes means that the test fails.

- [x] f347884 Simplify cli (#357)
- [ ] 2f9d7b9 Allow incomplete solutions in LS (#354)
- [ ] 0535b04 Cast measure (#356)
- [ ] b989713 Fix wrong load difference evaluation in SWAP* (#353)
- [ ] ae00385 Test within route two opt (#351)
- [ ] 597ec84 Add page with some guidelines and experiences implementing new VRP variants in PyVRP (#350)
- [ ] ad461cc Test descriptions (#349)
- [ ] 7f75c2e (alns) Improve rng (#347)
- [x] 5724b0f Make returned matrix non-writeable (#346)
- [x] a12c4fb Add Route destructor
- [ ] **PASS** 7bef1f0 Documentation fixes (#342)
- [ ] **PASS** 28f8aed Cast Matrix/np.ndarray (#338)
- [ ] **PASS** 10ab8c2 Add a SWAP* test that checks in-place swaps (#340)
- [ ] 8801e27 Update description of symbols we reserve for internal use
- [ ] **PASS** 5d67fe0 Simplify cli (#339)
- [ ] 0c86f94 Merge branch 'main' of github.com:PyVRP/PyVRP
- [ ] 248cf97 Remove superfluous helper
- [ ] 9eb94b2 Pickle support for Solution and Solution::Route (#337)
- [ ] **PASS** c8cd92b Simplify SWAP* (#302)

</details>

**Comment by N-Wouda** [comment]
Removing the destructor would mean any nodes contained in the route would still reference a by-then-nonexistent `Route` as their `route()` member. That's also not ideal.

**Comment by N-Wouda** [comment]
My first guess was that maybe we don't have the appropriate call/return value policies in place, but looking at the bindings I do not immediately see any issues with those.

**Comment by N-Wouda** [comment]
What *might* be the case is that we need to keep the route object alive when we add the node to it. I'm not entirely sure if _that_ is currently set up correctly.

**Comment by leonlan** [comment]
> Purely speculating, but what _might_ be the case is that we need to keep the route object alive when we add the node to it. I'm not entirely sure if that is currently set up correctly. I think that's something like `py::keep_alive<2, 1>`, and might need to be added to `append` and `insert`?

This works for me!

**Comment by leonlan** [comment]
> What's the issue with setting up a debugger exactly? 

The main problem was that after attaching to the Python process I can't get to step through the C++ source code. Tried this with terminal, VSCode, CLion. In some cases it just doesn't show anything, in other cases I get assembly (after which I then followed [this guide](https://werat.dev/blog/debugging-lldb-with-source-stepping/) to get source code to appear, but no success).

There were also [these steps](https://www.jetbrains.com/help/clion/debugging-python-extensions.html) to use CLion for debugging the C++ code. I followed both approaches in the guide, but neither worked because CLion doesn't hit/identify the breakpoints.

**Comment by N-Wouda** [comment]
I use [this extension](https://marketplace.visualstudio.com/items?itemName=benjamin-simmonds.pythoncpp-debug) in VS Code, but I'm not sure if that also helps in your case. I do think we need to figure out a way to get the debugger to work for you, because it's very helpful in figuring this sutff out.

In any case: TIL that Python on Mac has a really active garbage collector :-).

**Comment by leonlan** [comment]
> I use [this extension](https://marketplace.visualstudio.com/items?itemName=benjamin-simmonds.pythoncpp-debug) in VS Code, but I'm not sure if that also helps in your case. I do think we need to figure out a way to get the debugger to work for you, because it's very helpful in figuring this sutff out.

Yeah agreed, I'll look into this more the coming weeks!
